name: aliases
version: 0.8.1
about: dynamic alias functions for bash
author: Seb Glazebrook <me@sebglazebrook.com>

settings:
  - Hidden

subcommands:
  - init:
      about: initialize a directory for aliases
      args:
        - global:
            help: returns the global initialization for the app
            long: global
            short: g
            takes_value: false
        - user:
            help: initialize aliases for a specific user
            long: user
            short: u
            takes_value: true
  - list:
      about: list the aliases available
      args:
        - local:
            help: list only local aliases
            long: local
            short: l
            takes_value: false
            conflicts_with:
              - global
              - directory
        - global:
            help: list only global aliases
            long: global
            short: g
            takes_value: false
            conflicts_with:
              - local
              - directory
        - directory:
            help: list aliases for a specific directory
            long: directory
            short: d
            takes_value: true
            conflicts_with:
              - local
              - global
        - name:
            help: list aliases for with a specific name
            long: name
            short: n
            takes_value: true
  - users:
      about: list the users
      args: []
      subcommands:
        - move:
            about: move a user up or down the prioritization list
            args:
                - username:
                    help: user name you want to move
                    required: true
                - prioritization:
                    help: the priotity order you want for the user
                    required: true
        - use:
            about: Assign a user to the top of the priority list
            args:
                - username:
                    help: user name you want to move
                    required: true
        - enable:
            about: "Enable a user's aliases"
            args:
                - username:
                    help: user name you want to disable
                    required: true
        - disable:
            about: "Disable a user's aliases"
            args:
                - username:
                    help: user name you want to disable
                    required: true
  - exec:
      about: execute an alias for a given directory
      args:
        - directory:
            help: directory where the alias is defined
            required: true
        - name:
            help: name of alias
            required: true
            multiple: true
  - add:
      about: add an alias via the cli
      args:
        - name:
            help: the name of the alias
            required: true
        - command:
            help: the command you want to run
            required: true
  - remove:
      about: remove an alias via the cli
      args:
        - name:
            help: the name of the alias
            required: true
  - directories:
      about: list all directories initialized with aliases
  - rehash:
      about: update the aliases
      args: []
  - clone:
      about: clone external aliases
      args:
        - username:
            help: the username of the aliases you want to clone
            required: true
        - repo_url:
            help: the git repo url of the aliases (defaults to github/<username>/dot-aliases)
            required: false
        - enable:
            help: whether to enable the user if they are not currently enabled
            required: false
            long: enable
            short: E
  - pull:
      about: "pull a cloned user's aliases"
      args:
        - username:
            help: the username of the aliases you want to pull, leave blank to pull all user aliases
            required: false
