name: aliases
version: 0.8.0-devel
about: dynamic alias functions for bash
author: Seb Glazebrook <me@sebglazebrook.com>

settings:
  - Hidden

subcommands:
  - init:
      about: initialize a directory for aliases
      args:
        - global:
            help: returns the global initialzation for the app
            long: global
            short: g
            takes_value: false
        - user:
            help: initialize aliases for a specific user
            long: user
            short: u
            takes_value: true
  - list:
      about: list the aliases available
      args:
        - local:
            help: list only local aliases
            long: local
            short: l
            takes_value: false
        - global:
            help: list only global aliases
            long: gobal
            short: g
            takes_value: false
        - directory:
            help: list aliases for a specific directory
            long: directory
            short: d
            takes_value: true
        - name:
            help: list aliases for with a specific name
            long: name
            short: n
            takes_value: true
  - users:
      about: list the users
      args: []
      subcommands:
        - move:
            about: move a user up or down the prioritization list
            args:
                - username:
                    help: user name you want to move
                    required: true
                - prioritization:
                    help: the priotity order you want for the user
                    required: true
        - use:
            about: Assign a user to the top of the priority list
            args:
                - username:
                    help: user name you want to move
                    required: true
  - exec:
      about: execute an alias for a given directory
      args:
        - directory:
            help: directory where the alias is defined
            required: true
        - name:
            help: name of alias
            required: true
            multiple: true
  - rehash:
      about: update the aliases
      args: []
