name: aliases
version: 0.4.0
about: dynamic alias functions for bash
author: Seb Glazebrook <me@sebglazebrook.com>

subcommands:
  - init:
      about: initialize a directory for aliases
      args:
        - global:
            help: returns the global initialzation for the app
            long: global
            short: g
            takes_value: false
  - list:
      about: list the aliases available
      args:
        - local:
            help: list only local aliases
            long: local
            short: l
            takes_value: false
        - global:
            help: list only global aliases
            long: gobal
            short: g
            takes_value: false
        - directory:
            help: list aliases for a specific directory
            long: directory
            short: d
            takes_value: true
        - name:
            help: list aliases for with a specific name
            long: name
            short: n
            takes_value: true
  - exec:
      about: execute a alias for a given directory
      args:
        - directory:
            help: directory where the alias is defined
            required: true
        - name:
            help: name of alias
            required: true
  - rehash:
      about: update the aliases
      args: []
